export const unitConfigPresets = [
    {
        key: 'default',
        label: 'デフォルト',
        hp: 1,
        atk: 1,
        def: 1,
        spd: 2,
        cliRate: 1.5,
        cliDmg: 1.2,
        resist: 1,
        accuracy: 1,
        setLabels: [],
        mainType2Labels: [],
        mainType4Labels: [],
        mainType6Labels: [],
    },
    {
        key: 'cri-raid',
        label: 'クリダメアタッカー（異界レイド）',
        hp: 0.5,
        atk: 1,
        def: 0.5,
        spd: 1,
        cliRate: 1.2,
        cliDmg: 1.5,
        resist: 0,
        accuracy: 0,
        setLabels: ['激怒', '猛攻', '意志'],
        mainType2Labels: ['攻撃力%'],
        mainType4Labels: ['クリダメ'],
        mainType6Labels: ['攻撃力%'],
    },
    {
        key: 'lushen-kyojin',
        label: '巨人ワンパンルシェン',
        hp: 0.1,
        atk: 1,
        def: 0.1,
        spd: 2,
        cliRate: 1.5,
        cliDmg: 1.2,
        resist: 0,
        accuracy: 0,
        setLabels: ['激怒', '迅速', '猛攻', '2セットルーン'],
        mainType2Labels: ['攻撃力%'],
        mainType4Labels: ['クリダメ'],
        mainType6Labels: ['攻撃力%'],
    },
    {
        key: 'craca',
        label: 'クラカ',
        hp: 1,
        atk: 0.5,
        def: 1,
        spd: 2.5,
        cliRate: 1.5,
        cliDmg: 0.5,
        resist: 1,
        accuracy: 1,
        setLabels: ['絶望','2セットルーン'],
        mainType2Labels: ['速度','HP%'],
        mainType4Labels: ['HP%','クリ率'],
        mainType6Labels: ['HP%'],
    },
    {
        key: 'raki',
        label: 'ラキ',
        hp: 1,
        atk: 1.2,
        def: 1,
        spd: 1.5,
        cliRate: 2,
        cliDmg: 1,
        resist: 0.4,
        accuracy: 0.4,
        setLabels: ['激怒','意志'],
        mainType2Labels: ['HP%','攻撃力%'],
        mainType4Labels: ['クリダメ','クリ率'],
        mainType6Labels: ['HP%','攻撃力%'],
    },
    {
        key: 'windy',
        label: 'ウィンディ',
        hp: 1.5,
        atk: 0.2,
        def: 1,
        spd: 2.0,
        cliRate: 0.5,
        cliDmg: 0.2,
        resist: 1,
        accuracy: 0.2,
        setLabels: ['4セットルーン','2セットルーン'],
        mainType2Labels: ['速度','HP%'],
        mainType4Labels: ['HP%'],
        mainType6Labels: ['HP%'],
    },
    {
        key: 'hyanes',
        label: 'ヒアネス',
        hp: 1,
        atk: 0.1,
        def: 1,
        spd: 2.0,
        cliRate: 0.1,
        cliDmg: 0.1,
        resist: 0.5,
        accuracy: 1.2,
        setLabels: ['絶望','2セットルーン'],
        mainType2Labels: ['速度','HP%','防御力%'],
        mainType4Labels: ['HP%','防御力%'],
        mainType6Labels: ['HP%','防御力%'],
    },
    {
        key: 'ermeda',
        label: 'エルメダ',
        hp: 1.5,
        atk: 0.2,
        def: 1,
        spd: 1.5,
        cliRate: 0.5,
        cliDmg: 0.3,
        resist: 1,
        accuracy: 1,
        setLabels: ['絶望','2セットルーン'],
        mainType2Labels: ['HP%','防御力%'],
        mainType4Labels: ['HP%','防御力%'],
        mainType6Labels: ['HP%','防御力%'],
    },
    {
        key: 'varus',
        label: 'ヴァルス',
        hp: 1,
        atk: 0.5,
        def: 1.2,
        spd: 2,
        cliRate: 0,
        cliDmg: 1.2,
        resist: 0.5,
        accuracy: 1,
        setLabels: ['2セットルーン'],
        mainType2Labels: ['速度','防御力%'],
        mainType4Labels: ['防御力%'],
        mainType6Labels: ['防御力%'],
    },
    {
        key: 'vigoru',
        label: 'ヴィゴル',
        hp: 1.5,
        atk: 0.5,
        def: 1,
        spd: 2,
        cliRate: 1.5,
        cliDmg: 1,
        resist: 1,
        accuracy: 1,
        setLabels: ['暴走','迅速','2セットルーン'],
        mainType2Labels: ['速度','HP%'],
        mainType4Labels: ['HP%','クリダメ'],
        mainType6Labels: ['HP%'],
    },
    {
        key: 'kumunu',
        label: 'クムヌ',
        hp: 1.5,
        atk: 0.5,
        def: 1,
        spd: 2,
        cliRate: 1.5,
        cliDmg: 1,
        resist: 1,
        accuracy: 0.5,
        setLabels: ['迅速','2セットルーン'],
        mainType2Labels: ['速度','HP%'],
        mainType4Labels: ['HP%','クリダメ'],
        mainType6Labels: ['HP%'],
    },
    {
        key: 'bastet',
        label: 'バステト',
        hp: 1,
        atk: 0.5,
        def: 1,
        spd: 3,
        cliRate: 0.5,
        cliDmg: 0.2,
        resist: 0.5,
        accuracy: 1,
        setLabels: ['迅速','2セットルーン'],
        mainType2Labels: ['速度'],
        mainType4Labels: [],
        mainType6Labels: [],
    },
    {
        key: 'カルカノ',
        label: 'カルカノ',
        hp: 1,
        atk: 1,
        def: 1,
        spd: 2,
        cliRate: 2,
        cliDmg: 1,
        resist: 0.5,
        accuracy: 0.5,
        setLabels: ['暴走','意志','反撃'],
        mainType2Labels: ['速度', '攻撃力%'],
        mainType4Labels: ['クリダメ'],
        mainType6Labels: ['攻撃力%'],
    },
    {
        key: 'トリアーナ',
        label: 'トリアーナ',
        hp: 1,
        atk: 0.1,
        def: 1,
        spd: 2,
        cliRate: 0.5,
        cliDmg: 0.5,
        resist: 0.8,
        accuracy: 0.4,
        setLabels: ['暴走','迅速','意志'],
        mainType2Labels: ['速度', 'HP%'],
        mainType4Labels: ['HP%', '防御力%'],
        mainType6Labels: ['HP%', '防御力%']
    },
];
