export const unitConfigPresets = [
    {
        key: 'default',
        label: 'デフォルト',
        hp: 1,
        atk: 1,
        def: 1,
        spd: 2,
        cliRate: 1.5,
        cliDmg: 1.2,
        resist: 1,
        accuracy: 1,
        set: [],
        mainType2: [],
        mainType4: [],
        mainType6: [],
    },
    {
        key: 'cri-raid',
        label: 'クリダメアタッカー（異界レイド）',
        hp: 0.5,
        atk: 1,
        def: 0.5,
        spd: 1,
        cliRate: 1.2,
        cliDmg: 1.5,
        resist: 0,
        accuracy: 0,
        set: ['激怒', '猛攻', '意思'],
        mainType2: ['攻撃%'],
        mainType4: ['クリダメ'],
        mainType6: ['攻撃%'],
    },
    {
        key: 'lushen-kyojin',
        label: '巨人ワンパンルシェン',
        hp: 0.1,
        atk: 1,
        def: 0.1,
        spd: 2,
        cliRate: 1.2,
        cliDmg: 1.5,
        resist: 0,
        accuracy: 0,
        set: ['激怒', '迅速', '猛攻', '2セットルーン'],
        mainType2: ['攻撃%'],
        mainType4: ['クリダメ'],
        mainType6: ['攻撃%'],
    },
];
