import {UnitBuild} from './unit-build';
import {RuneEffect, RuneSet, set2Runes, set4Runes} from '../rune/rune';

export const unitBuildPresets: UnitBuild[] = [
    new UnitBuild({
        key: 'default', label: 'デフォルト',
        hp: 1, atk: 1, def: 1, spd: 2,
        cliRate: 1.5, cliDmg: 1.2, resist: 1, accuracy: 1,
        setLabels: [],
        mainTypes2: [],
        mainTypes4: [],
        mainTypes6: [],
    }),
    new UnitBuild({
        key: 'cri-raid', label: 'レイドクリダメ',
        hp: 0.5, atk: 1, def: 0.5, spd: 1,
        cliRate: 1.2, cliDmg: 1.5, resist: 0, accuracy: 0,
        setLabels: [RuneSet.激怒, RuneSet.猛攻, RuneSet.意志],
        mainTypes2: [RuneEffect['攻撃力%']],
        mainTypes4: [RuneEffect['クリダメ']],
        mainTypes6: [RuneEffect['攻撃力%']],
    }),
    new UnitBuild({
        key: 'lushen-one-pan', label: 'ワンパンルシェン',
        hp: 0.1, atk: 1, def: 0.1, spd: 2,
        cliRate: 1.5, cliDmg: 1.2, resist: 0, accuracy: 0,
        setLabels: [RuneSet.激怒, RuneSet.迅速, RuneSet.猛攻, ...set2Runes],
        mainTypes2: [RuneEffect['攻撃力%']],
        mainTypes4: [RuneEffect['クリダメ']],
        mainTypes6: [RuneEffect['攻撃力%']],
    }),
    new UnitBuild({
        key: 'craca', label: 'クラカ',
        hp: 1, atk: 0.5, def: 1, spd: 2.5,
        cliRate: 1.5, cliDmg: 0.5, resist: 1, accuracy: 1,
        setLabels: [RuneSet.絶望,RuneSet.意志,RuneSet.果報],
        mainTypes2: [RuneEffect['速度'],RuneEffect['HP%'], RuneEffect['防御力%']],
        mainTypes4: [RuneEffect['HP%'],RuneEffect['防御力%'], RuneEffect['クリ率']],
        mainTypes6: [RuneEffect['HP%'],RuneEffect['防御力%']],
    }),
    new UnitBuild({
        key: 'raki', label: 'ラキ',
        hp: 1, atk: 1.2, def: 1, spd: 1.5,
        cliRate: 2, cliDmg: 1, resist: 0.4, accuracy: 0.4,
        setLabels: [RuneSet.激怒,RuneSet.意志],
        mainTypes2: [RuneEffect['HP%'],RuneEffect['攻撃力%']],
        mainTypes4: [RuneEffect['クリダメ'],RuneEffect['クリ率']],
        mainTypes6: [RuneEffect['HP%'],RuneEffect['攻撃力%']],
    }),
    new UnitBuild({
        key: 'windy', label: 'ウィンディ',
        hp: 1.5, atk: 0.2, def: 1, spd: 2.0,
        cliRate: 0.5, cliDmg: 0.2, resist: 1, accuracy: 0.2,
        setLabels: [...set4Runes,...set2Runes],
        mainTypes2: [RuneEffect['速度'],RuneEffect['HP%']],
        mainTypes4: [RuneEffect['HP%']],
        mainTypes6: [RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'hyanes', label: 'ヒアネス',
        hp: 1, atk: 0.1, def: 1, spd: 2.0,
        cliRate: 0.1, cliDmg: 0.1, resist: 0.5, accuracy: 1.2,
        setLabels: [RuneSet.絶望,...set2Runes],
        mainTypes2: [RuneEffect['速度'],RuneEffect['HP%'],RuneEffect['防御力%']],
        mainTypes4: [RuneEffect['HP%'],RuneEffect['防御力%']],
        mainTypes6: [RuneEffect['HP%'],RuneEffect['防御力%']],
    }),
    new UnitBuild({
        key: 'ermeda', label: 'エルメダ',
        hp: 1.5, atk: 0.2, def: 1, spd: 1.5,
        cliRate: 0.5, cliDmg: 0.3, resist: 1, accuracy: 1,
        setLabels: [RuneSet.絶望,...set2Runes],
        mainTypes2: [RuneEffect['HP%'],RuneEffect['防御力%']],
        mainTypes4: [RuneEffect['HP%'],RuneEffect['防御力%']],
        mainTypes6: [RuneEffect['HP%'],RuneEffect['防御力%']],
    }),
    new UnitBuild({
        key: 'varus', label: 'ヴァルス',
        hp: 1, atk: 0.5, def: 1.2, spd: 2,
        cliRate: 0, cliDmg: 1.2, resist: 0.5, accuracy: 1,
        setLabels: [...set2Runes],
        mainTypes2: [RuneEffect['速度'],RuneEffect['防御力%']],
        mainTypes4: [RuneEffect['防御力%']],
        mainTypes6: [RuneEffect['防御力%']],
    }),
    new UnitBuild({
        key: 'vigoru', label: 'ヴィゴル',
        hp: 1.5, atk: 0.5, def: 1, spd: 2,
        cliRate: 1.5, cliDmg: 1, resist: 1, accuracy: 1,
        setLabels: [RuneSet.暴走,RuneSet.迅速,...set2Runes],
        mainTypes2: [RuneEffect['速度'],RuneEffect['HP%']],
        mainTypes4: [RuneEffect['HP%'],RuneEffect['クリダメ']],
        mainTypes6: [RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'kumunu', label: 'クムヌ',
        hp: 1.5, atk: 0.5, def: 1, spd: 2,
        cliRate: 1.5, cliDmg: 1, resist: 1, accuracy: 0.5,
        setLabels: [RuneSet.迅速,...set2Runes],
        mainTypes2: [RuneEffect['速度'],RuneEffect['HP%']],
        mainTypes4: [RuneEffect['HP%'],RuneEffect['クリダメ']],
        mainTypes6: [RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'bastet', label: 'バステト',
        hp: 1, atk: 0.5, def: 1, spd: 3,
        cliRate: 0.5, cliDmg: 0.2, resist: 0.5, accuracy: 1,
        setLabels: [RuneSet.迅速,...set2Runes],
        mainTypes2: [RuneEffect['速度']],
        mainTypes4: [RuneEffect['HP%']],
        mainTypes6: [RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'カルカノ', label: 'カルカノ',
        hp: 1, atk: 1, def: 1, spd: 2,
        cliRate: 2, cliDmg: 1, resist: 0.5, accuracy: 0.5,
        setLabels: [RuneSet.暴走,RuneSet.意志,RuneSet.反撃],
        mainTypes2: [RuneEffect['速度'], RuneEffect['攻撃力%']],
        mainTypes4: [RuneEffect['クリダメ']],
        mainTypes6: [RuneEffect['攻撃力%']],
    }),
    new UnitBuild({
        key: 'トリアーナ', label: 'トリアーナ',
        hp: 1, atk: 0.1, def: 1, spd: 2,
        cliRate: 0.5, cliDmg: 0.5, resist: 0.8, accuracy: 0.4,
        setLabels: [RuneSet.暴走,RuneSet.迅速,RuneSet.意志],
        mainTypes2: [RuneEffect['速度'], RuneEffect['HP%']],
        mainTypes4: [RuneEffect['HP%'], RuneEffect['防御力%']],
        mainTypes6: [RuneEffect['HP%'], RuneEffect['防御力%']]
    }),
    new UnitBuild({
        key: '絶望反撃ジュルタン', label: '絶望反撃ジュルタン',
        hp: 1.5, atk: 0.4, def: 1, spd: 1.5,
        cliRate: 0.5, cliDmg: 0.5, resist: 1, accuracy: 1,
        setLabels: [RuneSet.絶望,RuneSet.反撃],
        mainTypes2: [RuneEffect['HP%']],
        mainTypes4: [RuneEffect['HP%']],
        mainTypes6: [RuneEffect['HP%']]
    }),
    new UnitBuild({
        key: '余り物ジュルタン', label: '余り物ジュルタン',
        hp: 1.5, atk: 0.4, def: 1, spd: 1.5,
        cliRate: 0.5, cliDmg: 0.5, resist: 1, accuracy: 1,
        setLabels: [RuneSet.元気, RuneSet.果報, RuneSet.忍耐, RuneSet.集中, RuneSet.破壊, RuneSet.高揚],
        mainTypes2: [RuneEffect['HP%']],
        mainTypes4: [RuneEffect['HP%']],
        mainTypes6: [RuneEffect['HP%']]
    }),
    new UnitBuild({
        key: 'ブルコパ', label: 'ブルコパ',
        hp: 0.5, atk: 0, def: 1.2, spd: 0.8,
        cliRate: 1.5, cliDmg: 1.5, resist: 0.2, accuracy: 0.2,
        setLabels: [RuneSet.意志, RuneSet.激怒, RuneSet.守護, RuneSet.刃],
        mainTypes2: [RuneEffect['防御力%']],
        mainTypes4: [RuneEffect['クリダメ']],
        mainTypes6: [RuneEffect['防御力%']]
    }),
    new UnitBuild({
        key: 'ガロ', label: 'ガロ',
        hp: 0.2, atk: 1, def: 0.2, spd: 2,
        cliRate: 1, cliDmg: 1, resist: 0.2, accuracy: 0.4,
        setLabels: [RuneSet.吸血, RuneSet.刃, RuneSet.意志],
        mainTypes2: [RuneEffect['攻撃力%'], RuneEffect['速度']],
        mainTypes4: [RuneEffect['クリダメ']],
        mainTypes6: [RuneEffect['攻撃力%']]
    }),
    new UnitBuild({
        key: 'イカル', label: 'イカル',
        hp: 0, atk: 1, def: 2, spd: 0.5,
        cliRate: 1, cliDmg: 1, resist: 0.2, accuracy: 0.4,
        setLabels: [RuneSet.激怒, RuneSet.刃, RuneSet.守護, RuneSet.決意],
        mainTypes2: [RuneEffect['防御力%']],
        mainTypes4: [RuneEffect['防御力%'], RuneEffect['クリダメ']],
        mainTypes6: [RuneEffect['防御力%']]
    }),
    new UnitBuild({
        key: 'ベリアル', label: 'ベリアル',
        hp: 0, atk: 1, def: 0, spd: 1,
        cliRate: 1, cliDmg: 1, resist: 0, accuracy: 0,
        setLabels: [RuneSet.暴走, RuneSet.意志, RuneSet.刃, RuneSet.破壊],
        mainTypes2: [RuneEffect['攻撃力%']],
        mainTypes4: [RuneEffect['クリダメ']],
        mainTypes6: [RuneEffect['攻撃力%']]
    }),
    new UnitBuild({
        key: '水イフ', label: '水イフ',
        hp: 1, atk: 1, def: 1, spd: 2,
        cliRate: 1.2, cliDmg: 1, resist: 1, accuracy: 1,
        setLabels: [RuneSet.暴走, RuneSet.激怒, RuneSet.意志],
        mainTypes2: [RuneEffect['攻撃力%'], RuneEffect['速度']],
        mainTypes4: [RuneEffect['クリダメ']],
        mainTypes6: [RuneEffect['攻撃力%']]
    }),
    new UnitBuild({
        key: 'ミーナ', label: 'ミーナ',
        hp: 0.4, atk: 1, def: 0.4, spd: 2,
        cliRate: 0.5, cliDmg: 1.5, resist: 0.4, accuracy: 0.4,
        setLabels: [],
        mainTypes2: [RuneEffect['攻撃力%'], RuneEffect['速度']],
        mainTypes4: [RuneEffect['クリダメ']],
        mainTypes6: [RuneEffect['攻撃力%']]
    }),
    new UnitBuild({
        key: 'デコイ（的中ひかえめ）', label: 'デコイ（的中ひかえめ）',
        hp: 1, atk: 0.1, def: 1, spd: 1,
        cliRate: 0.1, cliDmg: 0.1, resist: 1, accuracy: 0.4,
        setLabels: [],
        mainTypes2: [RuneEffect['防御力%'], RuneEffect['HP%']],
        mainTypes4: [RuneEffect['防御力%'], RuneEffect['HP%']],
        mainTypes6: [RuneEffect['防御力%'], RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'エギル', label: 'エギル',
        hp: 1, atk: 1, def: 1, spd: 2,
        cliRate: 2, cliDmg: 1.2, resist: 0.5, accuracy: 0.5,
        setLabels: [RuneSet.猛攻],
        mainTypes2: [RuneEffect['攻撃力%'], RuneEffect['HP%']],
        mainTypes4: [RuneEffect['クリダメ'], RuneEffect['クリ率']],
        mainTypes6: [RuneEffect['攻撃力%'], RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'セアラ', label: 'セアラ',
        hp: 0.8, atk: 1.2, def: 0.8, spd: 2,
        cliRate: 1.5, cliDmg: 0.2, resist: 0.5, accuracy: 1,
        setLabels: [RuneSet.暴走, RuneSet.意志, RuneSet.反撃],
        mainTypes2: [RuneEffect['速度']],
        mainTypes4: [RuneEffect['クリ率'], RuneEffect['攻撃力%']],
        mainTypes6: [RuneEffect['攻撃力%'], RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'テサリオン', label: 'テサリオン',
        hp: 1, atk: 1, def: 1, spd: 2,
        cliRate: 1.5, cliDmg: 1, resist: 0.5, accuracy: 1,
        setLabels: [RuneSet.暴走, RuneSet.意志],
        mainTypes2: [RuneEffect['速度'],RuneEffect['HP%'],RuneEffect['攻撃力%'],RuneEffect['防御力%']],
        mainTypes4: [RuneEffect['クリ率'], RuneEffect['クリダメ'],RuneEffect['HP%'],RuneEffect['攻撃力%'],RuneEffect['防御力%']],
        mainTypes6: [RuneEffect['攻撃力%'], RuneEffect['HP%'],RuneEffect['速度']],
    }),
    new UnitBuild({
        key: 'ロイド', label: 'ロイド',
        hp: 1.2, atk: 0.4, def: 1, spd: 2,
        cliRate: 1.5, cliDmg: 1, resist: 0.5, accuracy: 1,
        setLabels: [],
        mainTypes2: [RuneEffect['HP%']],
        mainTypes4: [RuneEffect['クリ率'], RuneEffect['クリダメ'],RuneEffect['HP%']],
        mainTypes6: [RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'ジョン', label: 'ジョン',
        hp: 1, atk: 1.2, def: 1, spd: 2,
        cliRate: 0.2, cliDmg: 0.1, resist: 0.5, accuracy: 1.2,
        setLabels: [RuneSet.暴走, RuneSet.猛攻, ...set2Runes],
        mainTypes2: [RuneEffect.速度, RuneEffect['攻撃力%']],
        mainTypes4: [RuneEffect['攻撃力%']],
        mainTypes6: [RuneEffect['攻撃力%']],
    }),
    new UnitBuild({
        key: 'サポーター（要的中）', label: 'サポーター（要的中）',
        hp: 1, atk: 0.5, def: 1, spd: 2,
        cliRate: 0.2, cliDmg: 0.1, resist: 0.5, accuracy: 1,
        setLabels: [...set2Runes],
        mainTypes2: [RuneEffect.速度],
        mainTypes4: [RuneEffect['HP%'], RuneEffect['防御力%']],
        mainTypes6: [RuneEffect['HP%'], RuneEffect['防御力%']],
    }),
    new UnitBuild({
        key: 'ライリー', label: 'ライリー',
        hp: 1, atk: 0.2, def: 1, spd: 2,
        cliRate: 0.2, cliDmg: 0.1, resist: 0.7, accuracy: 0,
        setLabels: [RuneSet.暴走, RuneSet.意志],
        mainTypes2: [RuneEffect.速度],
        mainTypes4: [RuneEffect['HP%'], RuneEffect['防御力%']],
        mainTypes6: [RuneEffect['HP%'], RuneEffect['防御力%']],
    }),
    new UnitBuild({
        key: 'ノラ', label: 'ノラ',
        hp: 1, atk: 0.2, def: 1, spd: 2,
        cliRate: 0.2, cliDmg: 0.1, resist: 0.7, accuracy: 1,
        setLabels: [RuneSet.暴走, RuneSet.絶望, RuneSet.意志, RuneSet.反撃],
        mainTypes2: [RuneEffect.速度, RuneEffect['HP%']],
        mainTypes4: [RuneEffect['HP%'], RuneEffect['防御力%']],
        mainTypes6: [RuneEffect['HP%'], RuneEffect['防御力%']],
    }),
];
