import {UnitBuild} from './unit-build';
import {RuneEffect, RuneSet, set2Runes, set4Runes} from '../rune/rune';

export const unitBuildPresets: UnitBuild[] = [
    new UnitBuild({
        key: 'default', label: 'デフォルト',
        hp: 1, atk: 1, def: 1, spd: 2,
        cliRate: 1.5, cliDmg: 1.2, resist: 1, accuracy: 1,
        setLabels: [],
        mainType2Labels: [],
        mainType4Labels: [],
        mainType6Labels: [],
    }),
    new UnitBuild({
        key: 'cri-raid', label: 'クリダメアタッカー（異界レイド）',
        hp: 0.5, atk: 1, def: 0.5, spd: 1,
        cliRate: 1.2, cliDmg: 1.5, resist: 0, accuracy: 0,
        setLabels: [RuneSet.激怒, RuneSet.猛攻, RuneSet.意志],
        mainType2Labels: [RuneEffect['攻撃力%']],
        mainType4Labels: [RuneEffect['クリダメ']],
        mainType6Labels: [RuneEffect['攻撃力%']],
    }),
    new UnitBuild({
        key: 'lushen-kyojin', label: '巨人ワンパンルシェン',
        hp: 0.1, atk: 1, def: 0.1, spd: 2,
        cliRate: 1.5, cliDmg: 1.2, resist: 0, accuracy: 0,
        setLabels: [RuneSet.激怒, RuneSet.迅速, RuneSet.猛攻, ...set2Runes],
        mainType2Labels: [RuneEffect['攻撃力%']],
        mainType4Labels: [RuneEffect['クリダメ']],
        mainType6Labels: [RuneEffect['攻撃力%']],
    }),
    new UnitBuild({
        key: 'craca', label: 'クラカ',
        hp: 1, atk: 0.5, def: 1, spd: 2.5,
        cliRate: 1.5, cliDmg: 0.5, resist: 1, accuracy: 1,
        setLabels: [RuneSet.絶望,...set2Runes],
        mainType2Labels: [RuneEffect['速度'],RuneEffect['HP%']],
        mainType4Labels: [RuneEffect['HP%'],RuneEffect['クリ率']],
        mainType6Labels: [RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'raki', label: 'ラキ',
        hp: 1, atk: 1.2, def: 1, spd: 1.5,
        cliRate: 2, cliDmg: 1, resist: 0.4, accuracy: 0.4,
        setLabels: [RuneSet.激怒,RuneSet.意志],
        mainType2Labels: [RuneEffect['HP%'],RuneEffect['攻撃力%']],
        mainType4Labels: [RuneEffect['クリダメ'],RuneEffect['クリ率']],
        mainType6Labels: [RuneEffect['HP%'],RuneEffect['攻撃力%']],
    }),
    new UnitBuild({
        key: 'windy', label: 'ウィンディ',
        hp: 1.5, atk: 0.2, def: 1, spd: 2.0,
        cliRate: 0.5, cliDmg: 0.2, resist: 1, accuracy: 0.2,
        setLabels: [...set4Runes,...set2Runes],
        mainType2Labels: [RuneEffect['速度'],RuneEffect['HP%']],
        mainType4Labels: [RuneEffect['HP%']],
        mainType6Labels: [RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'hyanes', label: 'ヒアネス',
        hp: 1, atk: 0.1, def: 1, spd: 2.0,
        cliRate: 0.1, cliDmg: 0.1, resist: 0.5, accuracy: 1.2,
        setLabels: [RuneSet.絶望,...set2Runes],
        mainType2Labels: [RuneEffect['速度'],RuneEffect['HP%'],RuneEffect['防御力%']],
        mainType4Labels: [RuneEffect['HP%'],RuneEffect['防御力%']],
        mainType6Labels: [RuneEffect['HP%'],RuneEffect['防御力%']],
    }),
    new UnitBuild({
        key: 'ermeda', label: 'エルメダ',
        hp: 1.5, atk: 0.2, def: 1, spd: 1.5,
        cliRate: 0.5, cliDmg: 0.3, resist: 1, accuracy: 1,
        setLabels: [RuneSet.絶望,...set2Runes],
        mainType2Labels: [RuneEffect['HP%'],RuneEffect['防御力%']],
        mainType4Labels: [RuneEffect['HP%'],RuneEffect['防御力%']],
        mainType6Labels: [RuneEffect['HP%'],RuneEffect['防御力%']],
    }),
    new UnitBuild({
        key: 'varus', label: 'ヴァルス',
        hp: 1, atk: 0.5, def: 1.2, spd: 2,
        cliRate: 0, cliDmg: 1.2, resist: 0.5, accuracy: 1,
        setLabels: [...set2Runes],
        mainType2Labels: [RuneEffect['速度'],RuneEffect['防御力%']],
        mainType4Labels: [RuneEffect['防御力%']],
        mainType6Labels: [RuneEffect['防御力%']],
    }),
    new UnitBuild({
        key: 'vigoru', label: 'ヴィゴル',
        hp: 1.5, atk: 0.5, def: 1, spd: 2,
        cliRate: 1.5, cliDmg: 1, resist: 1, accuracy: 1,
        setLabels: [RuneSet.暴走,RuneSet.迅速,...set2Runes],
        mainType2Labels: [RuneEffect['速度'],RuneEffect['HP%']],
        mainType4Labels: [RuneEffect['HP%'],RuneEffect['クリダメ']],
        mainType6Labels: [RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'kumunu', label: 'クムヌ',
        hp: 1.5, atk: 0.5, def: 1, spd: 2,
        cliRate: 1.5, cliDmg: 1, resist: 1, accuracy: 0.5,
        setLabels: [RuneSet.迅速,...set2Runes],
        mainType2Labels: [RuneEffect['速度'],RuneEffect['HP%']],
        mainType4Labels: [RuneEffect['HP%'],RuneEffect['クリダメ']],
        mainType6Labels: [RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'bastet', label: 'バステト',
        hp: 1, atk: 0.5, def: 1, spd: 3,
        cliRate: 0.5, cliDmg: 0.2, resist: 0.5, accuracy: 1,
        setLabels: [RuneSet.迅速,...set2Runes],
        mainType2Labels: [RuneEffect['速度']],
        mainType4Labels: [RuneEffect['HP%']],
        mainType6Labels: [RuneEffect['HP%']],
    }),
    new UnitBuild({
        key: 'カルカノ', label: 'カルカノ',
        hp: 1, atk: 1, def: 1, spd: 2,
        cliRate: 2, cliDmg: 1, resist: 0.5, accuracy: 0.5,
        setLabels: [RuneSet.暴走,RuneSet.意志,RuneSet.反撃],
        mainType2Labels: [RuneEffect['速度'], RuneEffect['攻撃力%']],
        mainType4Labels: [RuneEffect['クリダメ']],
        mainType6Labels: [RuneEffect['攻撃力%']],
    }),
    new UnitBuild({
        key: 'トリアーナ', label: 'トリアーナ',
        hp: 1, atk: 0.1, def: 1, spd: 2,
        cliRate: 0.5, cliDmg: 0.5, resist: 0.8, accuracy: 0.4,
        setLabels: [RuneSet.暴走,RuneSet.迅速,RuneSet.意志],
        mainType2Labels: [RuneEffect['速度'], RuneEffect['HP%']],
        mainType4Labels: [RuneEffect['HP%'], RuneEffect['防御力%']],
        mainType6Labels: [RuneEffect['HP%'], RuneEffect['防御力%']]
    }),
];
